### ISSUE TITLE
Cannot Connect through Proxy

### ISSUE THREAD

**Issue by rweibel** [rosette-api/java#143]
I'm using this api through the Elasticsearch plugin, and it's failing to make it through the proxy. Inspecting the code, I can't find any reference to a proxy when the http request is being built.

It looks like the request should go here:
https://github.com/rosette-api/java/blob/6ec0e0e83dbc0c27c4150b680af115baeb0962bd/api/src/main/java/com/basistech/rosette/api/HttpRosetteAPI.java#L176-L187

Indeed, I modded the api in a local branch with:

```
        initHeaders(key, additionalHeaders);
        builder.setDefaultHeaders(this.additionalHeaders);

        String proxy = System.getProperty("HTTP_PROXY");
        String proxyPort = System.getProperty("HTTP_PROXY_PORT");
        if (proxy != null) {
            HttpHost proxyHost = HttpHost.create(proxy + ':' + proxyPort);
            builder.setProxy(proxyHost);
        }

        httpClient = builder.build();
        this.additionalHeaders = new ArrayList<>();
```
And it seems to connect fine.

**Comment by guruxu** [comment]
Thanks for reporting this issue and submitting a PR.

Since there are a lot of possible configurations for `HttpClient`, we have designed the API to have the default client be minimal. To change the default, you can simply bring your own `ClosableHttpClient` object that contains your desired configuration and use this builder method:

https://github.com/rosette-api/java/blob/6ec0e0e83dbc0c27c4150b680af115baeb0962bd/api/src/main/java/com/basistech/rosette/api/HttpRosetteAPI.java#L652-L661
